config/routes.rb
EasyMovies::Application.routes.draw do
  get "/carrito", to: "payments#carrito"
  get "/compras", to: "payments#compras"
  get "payments/express"
  get "transactions/checkout"
  resources :attachments
  resources :payments
  resources :posts

  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                      registrations: "registrations"}
  resources :usuario
  get "welcome/index"
  post "usuario/follow"

  root 'welcome#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :post
  belongs_to :usuario
  validates :post_id, presence: true
  validates :usuario_id, presence: true
  before_save :valores_por_default

  private
  def valores_por_default
    self.estado ||= 1
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    before_action :authenticate_usuario!

    def create
        @payment = current_usuario.payments.new(post_params)
        respond_to do |format|
            if @payment.save
                format.html { redirect_to carrito_path }
                format.json {head :no_content}
            else
                redirect_to Post.find(post_params[:post_id]), error: "No pudimos procesar tu compra"
                format.json {head :no_content}
            end
        end
    end
    def carrito
        @payments = current_usuario.payments.where(estado:1)
    end
    def compras
        @payments = current_usuario.payments.where(estado:2)
    end
    def express
        costo = current_usuario.costo_compra_pendiente
        response = EXPRESS_GATEWAY.setup_purchase(costo * 100,
            ip: request.remote_ip,
            return_url: "http://localhost:3000/transactions/checkout",
            cancel_return_url: "http://localhost:3000/carrito",
            name: "Checkout de compras en EasyDesign",
            amount: costo*100
        )
        redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token, review: false)
    end
    private
    def post_params
        params.require(:payment).permit(:post_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
    <% if payment.errors.any? %>
        <h2><%= pluralize(payment.errors.count, "error")%> evitaron que el pago se guardara </h2>
    <%end%>

    <div class="field">
        <%= f.hidden_field :post_id, value: post.id %>
    </div>
    <div class="actions">
        <%= content_tag :button, type: :submit, class: "btn btn-success" do%>
            <i class="fa fa-shopping-cart"></i> Comprar
        <%end%>
    </div>
<%end%>

app/views/payments/carrito.html.erb
<h1> <i class="fa fa-shopping-cart"></i> Mi carrito</h1>
<ul class="list-group">
    <% @payments.each do |payment| %>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-8">
                    <%= payment.post.title %>
                </div>
                <div class="col-md-3 text-right">
                    <%= "#{payment.post.costo}USD" unless payment.post.costo.nil? %>
                </div>
            </div>
        </li>
    <%end%>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-8">Total</div>
            <div class="col-md-3 text-right">
                <%= current_usuario.costo_compra_pendiente %>USD
            </div>
        </div>
    </li>
</ul>
<div class="text-center" data-no-turbolinks>
    <%= link_to(payments_express_path, class: "btn btn-success btn-lg") do %>
        <i class="fa fa-money"></i> Pagar
    <%end%>
</div>

app/views/payments/compras.html.erb
<h1> <i class="fa fa-shopping-cart"></i> Mis compras</h1>
<ul class="list-group">
    <% @payments.each do |payment| %>
        <li class="list-group-item">

            <%= link_to payment.post.titulo, payment.post %>

        </li>
    <%end%>

</ul>