config/routes.rb
EasyMovies::Application.routes.draw do
  get "/carrito", to: "payments#carrito"
  get "/compras", to: "payments#compras"
  get "payments/express"
  get "transactions/checkout"
  resources :attachments
  resources :payments
  resources :posts

  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                      registrations: "registrations"}
  resources :usuario
  get "welcome/index"
  post "usuario/follow"

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :usuario,  dependent: :destroy
  has_many :attachments
  has_many :payments
  validates :titulo, presence: true, uniqueness: true
  before_save :valores_por_default

  after_create {|post| post.message 'create'}


  include Picturable
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller,model| controller.current_usuario }

  def valores_por_default
    self.costo ||= 0
  end

  def usuarios_ha_pagado? usuario_id
    self.payments.where(estado: 2).size > 0
  end

  def message action
    msg = {
      resource: 'posts',
      action: action,
      id: self.id,
      obj: self,
      username: self.usuario.username.capitalize,
      user_id: self.usuario.id
    }

    $redis.publish 'rt-change', msg.to_json
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  #metodo de device
  before_action :authenticate_usuario!, except:[:show,:index]
  # include Devise::TestHelpers
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_usuario.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post creado con exito.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post modificado con exito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contenido, :archivo, :costo)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :archivo %>
    <%= f.file_field :archivo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :costo %>
    <%= f.number_field :costo, class: "form-control", step: "any" %>
  </div>
  <div class="form-group">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Subir post", class: "btn btn-info" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<ul class="list-group">
  <% @posts.each do |post| %>
    <li class="list-group-item">
      <%= link_to post.title, post %>
    </li>
  <%end%>
</ul>
<% if usuario_signed_in? %>
  <%= link_to 'Nuevo Post', new_post_path %>
<%end%>

app/views/posts/new.html.erb
<h1>Nuvo Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="jumbotron">
    <h1><%= @post.title %></h1>
    <div>
        <%= @post.contenido %>
    </div>

    <% if usuario_signed_in? %>
        <% if @post.usuarios_ha_pagado? current_usuario.id %>
            <% @post.attachments.each do |attachment| %>
                <%= link_to attachment.nombre, attachment %>
            <%end%>
        <%else%>
            <%= render "payments/form", payment: Payment.new, post: @post %>
        <%end%>

    <%end%>
</div>
<div class="text-right">
    <% if @post.usuario and usuario_signed_in? and @post.usuario == current_usuario  %>
        <%= link_to 'Editar', edit_post_path(@post) %> |
        <%= link_to 'Eliminar',@post, method: :delete, data: {confirm: "¿Estás seguro de borrar el post?"} %> |
    <%end%>
    <%= link_to 'Back', posts_path %>
</div>